---
- name: Setup Jenkins and Docker
  hosts: jenkins
  become: yes

  roles:
    - docker
    - jenkins
    - trivy

- name: Setup Docker and sonarqube
  hosts: sonarqube
  become: yes

  roles:
    - docker
    - sonarqube