---
- name: Install required packages
  apt:
    name: "{{ jenkins_packages }}"
    state: present
    update_cache: yes

- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    state: present
    filename: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - jenkins
    - ubuntu

- name: Create installation directory
  file:
    path: "{{ sonar_scanner_install_dir }}"
    state: directory
    mode: '0755'

- name: Download SonarScanner CLI
  get_url:
    url: "{{ sonar_scanner_url }}"
    dest: "/tmp/{{ sonar_scanner_zip_name }}.zip"
    mode: '0644'

- name: Extract SonarScanner CLI
  unarchive:
    src: "/tmp/{{ sonar_scanner_zip_name }}.zip"
    dest: "{{ sonar_scanner_install_dir }}"
    remote_src: true
    creates: "{{ sonar_scanner_install_dir }}/{{ sonar_scanner_dir_name }}"

- name: Create stable symlink
  file:
    src: "{{ sonar_scanner_install_dir }}/{{ sonar_scanner_dir_name }}"
    dest: "{{ sonar_scanner_symlink }}"
    state: link
    force: yes

- name: Create profile script for SonarScanner
  copy:
    dest: /etc/profile.d/sonar-scanner.sh
    mode: '0644'
    content: |
      export PATH={{ sonar_scanner_symlink }}/bin:$PATH

- name: Ensure scanner directory permissions
  file:
    path: "{{ sonar_scanner_install_dir }}/{{ sonar_scanner_dir_name }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: '0755'

- name: Verify sonar-scanner
  command: "{{ sonar_scanner_symlink }}/bin/sonar-scanner --version"
  register: sonar_scanner_installed_version
  changed_when: false

- name: Show installed sonar-scanner version
  debug:
    var: sonar_scanner_installed_version.stdout_lines